name: Embold Code Quality Scan

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:

jobs:
  embold-scan_fc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build with Maven (Skip Frontend and Tests)
        run: |
          mvn -B clean install \
            -DskipTests=true \
            -Dskip.npm=true \
            -Dskip.yarn=true \
            -Dskip.installnodenpm=true

      - name: Download and Extract Scanner
        run: |
          curl -sS ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET \
            "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/acc2ab8ea83e2adc72ea8c060fb8cdfb/scans/config/download" \
            --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" \
            -o repository-configuration.json

      - name: Run Embold Scanner
        run: |
          EMBOLD_TOKEN=${{ secrets.EMBOLD_TOKEN_JAVA }} \
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t $EMBOLD_TOKEN \
            -r acc2ab8ea83e2adc72ea8c060fb8cdfb \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home \
            -v
